=== napster2005/Amel-Reminder/analyses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:simpleType name="telTN">
    <xs:restriction base="xs:string">
        <xs:pattern value="\+216[0-9]{8}"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="emailType">
    <xs:restriction base="xs:string">
        <xs:pattern value="[^@]+@[^@]+\.[^@]+"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="statutType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="normal"/>
        <xs:enumeration value="surveiller"/>
        <xs:enumeration value="critique"/>
    </xs:restriction>
</xs:simpleType>

<xs:element name="analyses">
    <xs:complexType>
        <xs:sequence>

            <xs:element name="analyse" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>

                        <xs:element name="dateAnalyse">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="date" type="xs:date"/>
                                    <xs:element name="heure" type="xs:time"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>

                        <xs:element name="laboratoire">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nom" type="xs:string"/>
                                    <xs:element name="adresse" type="xs:string"/>
                                    <xs:element name="telephone" type="telTN"/>
                                    <xs:element name="fax" type="telTN"/>
                                    <xs:element name="email" type="emailType"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>

                        <xs:element name="typeAnalyse" type="xs:string"/>

                        <xs:element name="tests">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="test" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="valeur">
                                                    <xs:complexType>
                                                        <xs:simpleContent>
                                                            <xs:extension base="xs:decimal">
                                                                <xs:attribute name="unite" type="xs:string" use="required"/>
                                                            </xs:extension>
                                                        </xs:simpleContent>
                                                    </xs:complexType>
                                                </xs:element>
                                                <xs:element name="valeurUsuelle" type="xs:string"/>
                                            </xs:sequence>
                                            <xs:attribute name="nom" type="xs:string" use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>

                        <xs:element name="conclusion">
                            <xs:complexType mixed="true">
                                <xs:attribute name="statut" type="statutType" use="required"/>
                            </xs:complexType>
                        </xs:element>

                    </xs:sequence>

                    <xs:attribute name="id" type="xs:ID" use="required"/>

                </xs:complexType>
            </xs:element>

        </xs:sequence>

        <xs:attribute name="patientRef" type="xs:string" use="required"/>

    </xs:complexType>
</xs:element>

</xs:schema>

=== napster2005/Amel-Reminder/analyses2021.xml
<?xml version="1.0" encoding="UTF-8"?>
<analyses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="analyses.xsd"
patientRef="P01">

<analyse id="A2021_01">
<dateAnalyse><date>2021-01-15</date><heure>08:10:00</heure></dateAnalyse>
<laboratoire>
<nom>Hopital Regional de Djerba</nom>
<adresse>Djerba Tunisie</adresse>
<telephone>+21675600000</telephone>
<fax>+21675600001</fax>
<email>hopital.djerba@rns.tn</email>
</laboratoire>
<typeAnalyse>Hematologie</typeAnalyse>
<tests>
<test nom="Hemoglobine"><valeur unite="g/dL">11.2</valeur><valeurUsuelle>12 - 16</valeurUsuelle></test>
<test nom="Globules Blancs"><valeur unite="10^3/uL">3.5</valeur><valeurUsuelle>4 - 10</valeurUsuelle></test>
</tests>
<conclusion statut="surveiller">Debut anemie et baisse immunitaire</conclusion>
</analyse>

<analyse id="A2021_02">
<dateAnalyse><date>2021-02-10</date><heure>09:00:00</heure></dateAnalyse>
<laboratoire>
<nom>Laboratoire Pasteur</nom>
<adresse>Djerba Tunisie</adresse>
<telephone>+21675611111</telephone>
<fax>+21675622222</fax>
<email>pasteur.lab@gmail.com</email>
</laboratoire>
<typeAnalyse>Biochimie</typeAnalyse>
<tests>
<test nom="Ferritine"><valeur unite="ng/ml">18</valeur><valeurUsuelle>30 - 400</valeurUsuelle></test>
<test nom="CRP"><valeur unite="mg/L">7</valeur><valeurUsuelle>0 - 5</valeurUsuelle></test>
</tests>
<conclusion statut="surveiller">Inflammation et carence en fer</conclusion>
</analyse>

<analyse id="A2021_03">
<dateAnalyse><date>2021-03-12</date><heure>08:30:00</heure></dateAnalyse>
<laboratoire>
<nom>Laboratoire Bouzidi</nom>
<adresse>Zarzis Tunisie</adresse>
<telephone>+21675694329</telephone>
<fax>+21698430029</fax>
<email>labouzidihassen1@gmail.com</email>
</laboratoire>
<typeAnalyse>Hematologie</typeAnalyse>
<tests>
<test nom="Globules Rouges"><valeur unite="10^6/uL">4.2</valeur><valeurUsuelle>4.5 - 6</valeurUsuelle></test>
<test nom="Plaquettes"><valeur unite="10^3/uL">180</valeur><valeurUsuelle>150 - 400</valeurUsuelle></test>
</tests>
<conclusion statut="surveiller">Valeurs basses</conclusion>
</analyse>

<analyse id="A2021_04">
<dateAnalyse><date>2021-04-05</date><heure>10:00:00</heure></dateAnalyse>
<laboratoire>
<nom>Clinique Djerba</nom>
<adresse>Djerba Midoun</adresse>
<telephone>+21675700000</telephone>
<fax>+21675700001</fax>
<email>clinique@djerba.tn</email>
</laboratoire>
<typeAnalyse>Renal</typeAnalyse>
<tests>
<test nom="Creatinine"><valeur unite="mg/L">11</valeur><valeurUsuelle>6 - 12</valeurUsuelle></test>
<test nom="Uree"><valeur unite="g/L">0.40</valeur><valeurUsuelle>0.15 - 0.45</valeurUsuelle></test>
</tests>
<conclusion statut="normal">Fonction renale normale</conclusion>
</analyse>

<analyse id="A2021_05">
<dateAnalyse><date>2021-05-18</date><heure>09:45:00</heure></dateAnalyse>
<laboratoire>
<nom>Laboratoire Pasteur</nom>
<adresse>Djerba Tunisie</adresse>
<telephone>+21675611111</telephone>
<fax>+21675622222</fax>
<email>pasteur.lab@gmail.com</email>
</laboratoire>
<typeAnalyse>Marqueur Tumoral</typeAnalyse>
<tests>
<test nom="CEA"><valeur unite="ng/ml">5.5</valeur><valeurUsuelle>0 - 3</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Marqueur eleve</conclusion>
</analyse>

<analyse id="A2021_06">
<dateAnalyse><date>2021-06-10</date><heure>09:30:00</heure></dateAnalyse>
<laboratoire>
<nom>Laboratoire Bouzidi</nom>
<adresse>Zarzis Tunisie</adresse>
<telephone>+21675694329</telephone>
<fax>+21698430029</fax>
<email>labouzidihassen1@gmail.com</email>
</laboratoire>
<typeAnalyse>Hormonologie</typeAnalyse>
<tests>
<test nom="TSH"><valeur unite="uIU/ml">0.60</valeur><valeurUsuelle>0.34 - 5.60</valeurUsuelle></test>
<test nom="FT4"><valeur unite="pmol/L">16</valeur><valeurUsuelle>12 - 22</valeurUsuelle></test>
</tests>
<conclusion statut="normal">Fonction hormonale stable</conclusion>
</analyse>

<analyse id="A2021_07">
<dateAnalyse><date>2021-07-20</date><heure>08:50:00</heure></dateAnalyse>
<laboratoire>
<nom>Hopital Regional de Djerba</nom>
<adresse>Djerba Tunisie</adresse>
<telephone>+21675600000</telephone>
<fax>+21675600001</fax>
<email>hopital.djerba@rns.tn</email>
</laboratoire>
<typeAnalyse>Biochimie</typeAnalyse>
<tests>
<test nom="Albumine"><valeur unite="g/L">30</valeur><valeurUsuelle>35 - 50</valeurUsuelle></test>
</tests>
<conclusion statut="surveiller">Etat nutritionnel faible</conclusion>
</analyse>

<analyse id="A2021_08">
<dateAnalyse><date>2021-08-11</date><heure>09:15:00</heure></dateAnalyse>
<laboratoire>
<nom>Clinique Djerba</nom>
<adresse>Djerba Midoun</adresse>
<telephone>+21675700000</telephone>
<fax>+21675700001</fax>
<email>clinique@djerba.tn</email>
</laboratoire>
<typeAnalyse>Inflammation</typeAnalyse>
<tests>
<test nom="CRP"><valeur unite="mg/L">9</valeur><valeurUsuelle>0 - 5</valeurUsuelle></test>
</tests>
<conclusion statut="surveiller">Inflammation persistante</conclusion>
</analyse>

<analyse id="A2021_09">
<dateAnalyse><date>2021-09-03</date><heure>08:20:00</heure></dateAnalyse>
<laboratoire>
<nom>Laboratoire Pasteur</nom>
<adresse>Djerba Tunisie</adresse>
<telephone>+21675611111</telephone>
<fax>+21675622222</fax>
<email>pasteur.lab@gmail.com</email>
</laboratoire>
<typeAnalyse>Hematologie</typeAnalyse>
<tests>
<test nom="Hemoglobine"><valeur unite="g/dL">10.8</valeur><valeurUsuelle>12 - 16</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Anemie aggravee</conclusion>
</analyse>

<analyse id="A2021_10">
<dateAnalyse><date>2021-10-14</date><heure>09:10:00</heure></dateAnalyse>
<laboratoire>
<nom>Hopital Regional de Djerba</nom>
<adresse>Djerba Tunisie</adresse>
<telephone>+21675600000</telephone>
<fax>+21675600001</fax>
<email>hopital.djerba@rns.tn</email>
</laboratoire>
<typeAnalyse>Glycemie</typeAnalyse>
<tests>
<test nom="Glycemie"><valeur unite="g/L">1.2</valeur><valeurUsuelle>0.7 - 1.1</valeurUsuelle></test>
</tests>
<conclusion statut="surveiller">Hyperglycemie legere</conclusion>
</analyse>

<analyse id="A2021_11">
<dateAnalyse><date>2021-11-01</date><heure>08:40:00</heure></dateAnalyse>
<laboratoire>
<nom>Laboratoire Bouzidi</nom>
<adresse>Zarzis Tunisie</adresse>
<telephone>+21675694329</telephone>
<fax>+21698430029</fax>
<email>labouzidihassen1@gmail.com</email>
</laboratoire>
<typeAnalyse>Fer</typeAnalyse>
<tests>
<test nom="Ferritine"><valeur unite="ng/ml">15</valeur><valeurUsuelle>30 - 400</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Carence severe en fer</conclusion>
</analyse>

<analyse id="A2021_12">
<dateAnalyse><date>2021-11-20</date><heure>09:00:00</heure></dateAnalyse>
<laboratoire>
<nom>Clinique Djerba</nom>
<adresse>Djerba Midoun</adresse>
<telephone>+21675700000</telephone>
<fax>+21675700001</fax>
<email>clinique@djerba.tn</email>
</laboratoire>
<typeAnalyse>Hematologie</typeAnalyse>
<tests>
<test nom="Globules Blancs"><valeur unite="10^3/uL">3.2</valeur><valeurUsuelle>4 - 10</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Immunite tres faible</conclusion>
</analyse>

<analyse id="A2021_13">
<dateAnalyse><date>2021-12-05</date><heure>08:30:00</heure></dateAnalyse>
<laboratoire>
<nom>Hopital Regional de Djerba</nom>
<adresse>Djerba Tunisie</adresse>
<telephone>+21675600000</telephone>
<fax>+21675600001</fax>
<email>hopital.djerba@rns.tn</email>
</laboratoire>
<typeAnalyse>Renal</typeAnalyse>
<tests>
<test nom="Creatinine"><valeur unite="mg/L">10</valeur><valeurUsuelle>6 - 12</valeurUsuelle></test>
</tests>
<conclusion statut="normal">Stable</conclusion>
</analyse>

<analyse id="A2021_14">
<dateAnalyse><date>2021-12-15</date><heure>09:20:00</heure></dateAnalyse>
<laboratoire>
<nom>Laboratoire Pasteur</nom>
<adresse>Djerba Tunisie</adresse>
<telephone>+21675611111</telephone>
<fax>+21675622222</fax>
<email>pasteur.lab@gmail.com</email>
</laboratoire>
<typeAnalyse>Marqueur Tumoral</typeAnalyse>
<tests>
<test nom="CA19-9"><valeur unite="U/ml">45</valeur><valeurUsuelle>0 - 37</valeurUsuelle></test>
</tests>
<conclusion statut="surveiller">Valeur elevee</conclusion>
</analyse>

<analyse id="A2021_15">
<dateAnalyse><date>2021-12-28</date><heure>08:55:00</heure></dateAnalyse>
<laboratoire>
<nom>Laboratoire Bouzidi</nom>
<adresse>Zarzis Tunisie</adresse>
<telephone>+21675694329</telephone>
<fax>+21698430029</fax>
<email>labouzidihassen1@gmail.com</email>
</laboratoire>
<typeAnalyse>Biochimie</typeAnalyse>
<tests>
<test nom="Vitamine B12"><valeur unite="pg/ml">190</valeur><valeurUsuelle>174 - 878</valeurUsuelle></test>
</tests>
<conclusion statut="surveiller">Limite basse</conclusion>
</analyse>

</analyses>

=== napster2005/Amel-Reminder/analyses2023.xml
<?xml version="1.0" encoding="UTF-8"?>

<analyses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="analyses.xsd"
patientRef="P01">

<analyse id="A2023_01">
<dateAnalyse><date>2023-01-10</date><heure>08:00:00</heure></dateAnalyse>
<laboratoire><nom>Hopital Regional de Djerba</nom><adresse>Djerba Tunisie</adresse><telephone>+21675600000</telephone><fax>+21675600001</fax><email>hopital.djerba@rns.tn</email></laboratoire>
<typeAnalyse>Hematologie</typeAnalyse>
<tests>
<test nom="Hemoglobine"><valeur unite="g/dL">9.0</valeur><valeurUsuelle>12 - 16</valeurUsuelle></test>
<test nom="Hematocrite"><valeur unite="%">28</valeur><valeurUsuelle>36 - 46</valeurUsuelle></test>
<test nom="VGM"><valeur unite="fL">78</valeur><valeurUsuelle>80 - 100</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Anemie severe microcytaire</conclusion>
</analyse>

<analyse id="A2023_02">
<dateAnalyse><date>2023-01-25</date><heure>09:10:00</heure></dateAnalyse>
<laboratoire><nom>Laboratoire Pasteur</nom><adresse>Djerba Tunisie</adresse><telephone>+21675611111</telephone><fax>+21675622222</fax><email>pasteur.lab@gmail.com</email></laboratoire>
<typeAnalyse>Biochimie</typeAnalyse>
<tests>
<test nom="Glucose"><valeur unite="g/L">1.5</valeur><valeurUsuelle>0.7 - 1.1</valeurUsuelle></test>
<test nom="Cholesterol"><valeur unite="g/L">2.4</valeur><valeurUsuelle>1.5 - 2</valeurUsuelle></test>
</tests>
<conclusion statut="surveiller">Hyperglycemie et hyperlipidemie</conclusion>
</analyse>

<analyse id="A2023_03">
<dateAnalyse><date>2023-02-14</date><heure>08:45:00</heure></dateAnalyse>
<laboratoire><nom>Laboratoire Bouzidi</nom><adresse>Zarzis Tunisie</adresse><telephone>+21675694329</telephone><fax>+21698430029</fax><email>labouzidihassen1@gmail.com</email></laboratoire>
<typeAnalyse>Immunologie</typeAnalyse>
<tests>
<test nom="Lymphocytes"><valeur unite="10^3/uL">0.6</valeur><valeurUsuelle>1.5 - 4</valeurUsuelle></test>
<test nom="CD4"><valeur unite="cells/mm3">180</valeur><valeurUsuelle>500 - 1500</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Deficit immunitaire severe</conclusion>
</analyse>

<analyse id="A2023_04">
<dateAnalyse><date>2023-03-05</date><heure>10:00:00</heure></dateAnalyse>
<laboratoire><nom>Clinique Djerba</nom><adresse>Djerba Midoun</adresse><telephone>+21675700000</telephone><fax>+21675700001</fax><email>clinique@djerba.tn</email></laboratoire>
<typeAnalyse>Renal</typeAnalyse>
<tests>
<test nom="Creatinine"><valeur unite="mg/L">15</valeur><valeurUsuelle>6 - 12</valeurUsuelle></test>
<test nom="Uree"><valeur unite="g/L">0.65</valeur><valeurUsuelle>0.15 - 0.45</valeurUsuelle></test>
<test nom="DFG"><valeur unite="ml/min">50</valeur><valeurUsuelle>90 - 120</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Insuffisance renale</conclusion>
</analyse>

<analyse id="A2023_05">
<dateAnalyse><date>2023-03-25</date><heure>09:30:00</heure></dateAnalyse>
<laboratoire><nom>Laboratoire Pasteur</nom><adresse>Djerba Tunisie</adresse><telephone>+21675611111</telephone><fax>+21675622222</fax><email>pasteur.lab@gmail.com</email></laboratoire>
<typeAnalyse>Marqueur Tumoral</typeAnalyse>
<tests>
<test nom="CEA"><valeur unite="ng/ml">9.2</valeur><valeurUsuelle>0 - 3</valeurUsuelle></test>
<test nom="CA125"><valeur unite="U/ml">60</valeur><valeurUsuelle>0 - 35</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Progression tumorale</conclusion>
</analyse>

<analyse id="A2023_06">
<dateAnalyse><date>2023-04-18</date><heure>08:20:00</heure></dateAnalyse>
<laboratoire><nom>Hopital Regional de Djerba</nom><adresse>Djerba Tunisie</adresse><telephone>+21675600000</telephone><fax>+21675600001</fax><email>hopital.djerba@rns.tn</email></laboratoire>
<typeAnalyse>Hormonologie</typeAnalyse>
<tests>
<test nom="TSH"><valeur unite="uIU/ml">0.25</valeur><valeurUsuelle>0.34 - 5.60</valeurUsuelle></test>
<test nom="Cortisol"><valeur unite="µg/dL">5</valeur><valeurUsuelle>10 - 20</valeurUsuelle></test>
</tests>
<conclusion statut="surveiller">Desequilibre hormonal</conclusion>
</analyse>

<analyse id="A2023_07">
<dateAnalyse><date>2023-05-02</date><heure>09:00:00</heure></dateAnalyse>
<laboratoire><nom>Laboratoire Bouzidi</nom><adresse>Zarzis Tunisie</adresse><telephone>+21675694329</telephone><fax>+21698430029</fax><email>labouzidihassen1@gmail.com</email></laboratoire>
<typeAnalyse>Fer</typeAnalyse>
<tests>
<test nom="Ferritine"><valeur unite="ng/ml">6</valeur><valeurUsuelle>30 - 400</valeurUsuelle></test>
<test nom="Transferrine"><valeur unite="g/L">4.0</valeur><valeurUsuelle>2 - 3.6</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Carence severe en fer</conclusion>
</analyse>

<analyse id="A2023_08">
<dateAnalyse><date>2023-06-10</date><heure>09:20:00</heure></dateAnalyse>
<laboratoire><nom>Clinique Djerba</nom><adresse>Djerba Midoun</adresse><telephone>+21675700000</telephone><fax>+21675700001</fax><email>clinique@djerba.tn</email></laboratoire>
<typeAnalyse>Electrolytes</typeAnalyse>
<tests>
<test nom="Sodium"><valeur unite="mmol/L">128</valeur><valeurUsuelle>135 - 145</valeurUsuelle></test>
<test nom="Potassium"><valeur unite="mmol/L">5.8</valeur><valeurUsuelle>3.5 - 5</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Desequilibre ionique</conclusion>
</analyse>

<analyse id="A2023_09">
<dateAnalyse><date>2023-07-15</date><heure>08:30:00</heure></dateAnalyse>
<laboratoire><nom>Laboratoire Pasteur</nom><adresse>Djerba Tunisie</adresse><telephone>+21675611111</telephone><fax>+21675622222</fax><email>pasteur.lab@gmail.com</email></laboratoire>
<typeAnalyse>Vitamine</typeAnalyse>
<tests>
<test nom="Vitamine D"><valeur unite="ng/ml">9</valeur><valeurUsuelle>30 - 100</valeurUsuelle></test>
<test nom="Vitamine B12"><valeur unite="pg/ml">150</valeur><valeurUsuelle>174 - 878</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Carences multiples</conclusion>
</analyse>

<analyse id="A2023_10">
<dateAnalyse><date>2023-09-01</date><heure>09:00:00</heure></dateAnalyse>
<laboratoire><nom>Hopital Regional de Djerba</nom><adresse>Djerba Tunisie</adresse><telephone>+21675600000</telephone><fax>+21675600001</fax><email>hopital.djerba@rns.tn</email></laboratoire>
<typeAnalyse>Coagulation</typeAnalyse>
<tests>
<test nom="TP"><valeur unite="%">60</valeur><valeurUsuelle>70 - 100</valeurUsuelle></test>
<test nom="INR"><valeur unite="">1.6</valeur><valeurUsuelle>0.8 - 1.2</valeurUsuelle></test>
</tests>
<conclusion statut="surveiller">Trouble de coagulation</conclusion>
</analyse>

<analyse id="A2023_11">
<dateAnalyse><date>2023-10-12</date><heure>08:50:00</heure></dateAnalyse>
<laboratoire><nom>Laboratoire Bouzidi</nom><adresse>Zarzis Tunisie</adresse><telephone>+21675694329</telephone><fax>+21698430029</fax><email>labouzidihassen1@gmail.com</email></laboratoire>
<typeAnalyse>Hematologie</typeAnalyse>
<tests>
<test nom="Plaquettes"><valeur unite="10^3/uL">110</valeur><valeurUsuelle>150 - 400</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Thrombopenie</conclusion>
</analyse>

</analyses>
