=== napster2005/Amel-Reminder/analyses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:simpleType name="telTN">
    <xs:restriction base="xs:string">
        <xs:pattern value="\+216[0-9]{8}"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="emailType">
    <xs:restriction base="xs:string">
        <xs:pattern value="[^@]+@[^@]+\.[^@]+"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="statutType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="normal"/>
        <xs:enumeration value="surveiller"/>
        <xs:enumeration value="critique"/>
    </xs:restriction>
</xs:simpleType>

<xs:element name="analyses">
    <xs:complexType>
        <xs:sequence>

            <xs:element name="analyse" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>

                        <xs:element name="dateAnalyse">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="date" type="xs:date"/>
                                    <xs:element name="heure" type="xs:time"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>

                        <xs:element name="laboratoire">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nom" type="xs:string"/>
                                    <xs:element name="adresse" type="xs:string"/>
                                    <xs:element name="telephone" type="telTN"/>
                                    <xs:element name="fax" type="telTN"/>
                                    <xs:element name="email" type="emailType"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>

                        <xs:element name="typeAnalyse" type="xs:string"/>

                        <xs:element name="tests">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="test" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="valeur">
                                                    <xs:complexType>
                                                        <xs:simpleContent>
                                                            <xs:extension base="xs:decimal">
                                                                <xs:attribute name="unite" type="xs:string" use="required"/>
                                                            </xs:extension>
                                                        </xs:simpleContent>
                                                    </xs:complexType>
                                                </xs:element>
                                                <xs:element name="valeurUsuelle" type="xs:string"/>
                                            </xs:sequence>
                                            <xs:attribute name="nom" type="xs:string" use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>

                        <xs:element name="conclusion">
                            <xs:complexType mixed="true">
                                <xs:attribute name="statut" type="statutType" use="required"/>
                            </xs:complexType>
                        </xs:element>

                    </xs:sequence>

                    <xs:attribute name="id" type="xs:ID" use="required"/>

                </xs:complexType>
            </xs:element>

        </xs:sequence>

        <xs:attribute name="patientRef" type="xs:string" use="required"/>

    </xs:complexType>
</xs:element>

</xs:schema>

=== napster2005/Amel-Reminder/analyses2024.xml
<?xml version="1.0" encoding="UTF-8"?>

<analyses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="analyses.xsd"
patientRef="P01">

<analyse id="A2024_01">
    <dateAnalyse>
        <date>2024-01-12</date>
        <heure>08:15:00</heure>
    </dateAnalyse>
    <laboratoire>
        <nom>Hopital Universitaire Sfax</nom>
        <adresse>Sfax Tunisie</adresse>
        <telephone>+21674200000</telephone>
        <fax>+21674200001</fax>
        <email>chu.sfax@rns.tn</email>
    </laboratoire>
    <typeAnalyse>Hematologie</typeAnalyse>
    <tests>
        <test nom="Hemoglobine">
            <valeur unite="g/dL">11.2</valeur>
            <valeurUsuelle>12 - 16</valeurUsuelle>
        </test>
        <test nom="Leucocytes">
            <valeur unite="10^3/uL">13</valeur>
            <valeurUsuelle>4 - 10</valeurUsuelle>
        </test>
    </tests>
    <conclusion statut="surveiller">Anemie legere et infection possible</conclusion>
</analyse>

<analyse id="A2024_02">
    <dateAnalyse>
        <date>2024-02-05</date>
        <heure>09:00:00</heure>
    </dateAnalyse>
    <laboratoire>
        <nom>Laboratoire Ennasr</nom>
        <adresse>Tunis Tunisie</adresse>
        <telephone>+21671234567</telephone>
        <fax>+21671234568</fax>
        <email>lab.ennasr@gmail.com</email>
    </laboratoire>
    <typeAnalyse>Biochimie</typeAnalyse>
    <tests>
        <test nom="Glucose">
            <valeur unite="g/L">0.95</valeur>
            <valeurUsuelle>0.7 - 1.1</valeurUsuelle>
        </test>
        <test nom="Triglycerides">
            <valeur unite="g/L">1.8</valeur>
            <valeurUsuelle>0.5 - 1.5</valeurUsuelle>
        </test>
    </tests>
    <conclusion statut="normal">Bilan globalement normal</conclusion>
</analyse>

<analyse id="A2024_03">
    <dateAnalyse>
        <date>2024-03-18</date>
        <heure>08:40:00</heure>
    </dateAnalyse>
    <laboratoire>
        <nom>Clinique Ariana</nom>
        <adresse>Ariana Tunisie</adresse>
        <telephone>+21671300000</telephone>
        <fax>+21671300001</fax>
        <email>clinique.ariana@gmail.com</email>
    </laboratoire>
    <typeAnalyse>Cardiaque</typeAnalyse>
    <tests>
        <test nom="Troponine">
            <valeur unite="ng/ml">0.8</valeur>
            <valeurUsuelle>0 - 0.04</valeurUsuelle>
        </test>
    </tests>
    <conclusion statut="critique">Suspicion infarctus</conclusion>
</analyse>

<analyse id="A2024_04">
    <dateAnalyse>
        <date>2024-04-10</date>
        <heure>10:10:00</heure>
    </dateAnalyse>
    <laboratoire>
        <nom>Laboratoire Pasteur</nom>
        <adresse>Tunis Tunisie</adresse>
        <telephone>+21675611111</telephone>
        <fax>+21675622222</fax>
        <email>pasteur.lab@gmail.com</email>
    </laboratoire>
    <typeAnalyse>Renal</typeAnalyse>
    <tests>
        <test nom="Creatinine">
            <valeur unite="mg/L">11</valeur>
            <valeurUsuelle>6 - 12</valeurUsuelle>
        </test>
        <test nom="Uree">
            <valeur unite="g/L">0.4</valeur>
            <valeurUsuelle>0.15 - 0.45</valeurUsuelle>
        </test>
    </tests>
    <conclusion statut="normal">Fonction renale normale</conclusion>
</analyse>

<analyse id="A2024_05">
    <dateAnalyse>
        <date>2024-05-22</date>
        <heure>09:25:00</heure>
    </dateAnalyse>
    <laboratoire>
        <nom>Hopital La Rabta</nom>
        <adresse>Tunis Tunisie</adresse>
        <telephone>+21671578900</telephone>
        <fax>+21671578901</fax>
        <email>rabta@rns.tn</email>
    </laboratoire>
    <typeAnalyse>Immunologie</typeAnalyse>
    <tests>
        <test nom="CRP">
            <valeur unite="mg/L">45</valeur>
            <valeurUsuelle>0 - 5</valeurUsuelle>
        </test>
    </tests>
    <conclusion statut="critique">Inflammation severe</conclusion>
</analyse>

<analyse id="A2024_06">
    <dateAnalyse>
        <date>2024-06-30</date>
        <heure>08:50:00</heure>
    </dateAnalyse>
    <laboratoire>
        <nom>Laboratoire Bouzidi</nom>
        <adresse>Zarzis Tunisie</adresse>
        <telephone>+21675694329</telephone>
        <fax>+21698430029</fax>
        <email>labouzidihassen1@gmail.com</email>
    </laboratoire>
    <typeAnalyse>Hormonal</typeAnalyse>
    <tests>
        <test nom="TSH">
            <valeur unite="uIU/ml">3.2</valeur>
            <valeurUsuelle>0.34 - 5.60</valeurUsuelle>
        </test>
    </tests>
    <conclusion statut="normal">Fonction thyroidienne normale</conclusion>
</analyse>

<analyse id="A2024_07">
    <dateAnalyse>
        <date>2024-07-15</date>
        <heure>09:10:00</heure>
    </dateAnalyse>
    <laboratoire>
        <nom>Clinique Djerba</nom>
        <adresse>Djerba Midoun</adresse>
        <telephone>+21675700000</telephone>
        <fax>+21675700001</fax>
        <email>clinique@djerba.tn</email>
    </laboratoire>
    <typeAnalyse>Electrolytes</typeAnalyse>
    <tests>
        <test nom="Sodium">
            <valeur unite="mmol/L">140</valeur>
            <valeurUsuelle>135 - 145</valeurUsuelle>
        </test>
        <test nom="Potassium">
            <valeur unite="mmol/L">4.2</valeur>
            <valeurUsuelle>3.5 - 5</valeurUsuelle>
        </test>
    </tests>
    <conclusion statut="normal">Equilibre ionique normal</conclusion>
</analyse>

<analyse id="A2024_08">
    <dateAnalyse>
        <date>2024-09-05</date>
        <heure>08:30:00</heure>
    </dateAnalyse>
    <laboratoire>
        <nom>Hopital Regional de Djerba</nom>
        <adresse>Djerba Tunisie</adresse>
        <telephone>+21675600000</telephone>
        <fax>+21675600001</fax>
        <email>hopital.djerba@rns.tn</email>
    </laboratoire>
    <typeAnalyse>Vitamine</typeAnalyse>
    <tests>
        <test nom="Vitamine D">
            <valeur unite="ng/ml">32</valeur>
            <valeurUsuelle>30 - 100</valeurUsuelle>
        </test>
    </tests>
    <conclusion statut="normal">Niveau vitaminique correct</conclusion>
</analyse>

</analyses>

=== napster2005/Amel-Reminder/analyses2022.xml
<?xml version="1.0" encoding="UTF-8"?>

<analyses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="analyses.xsd"
patientRef="P01">

<analyse id="A2022_01">
<dateAnalyse><date>2022-01-10</date><heure>08:10:00</heure></dateAnalyse>
<laboratoire>
<nom>Hopital Regional de Djerba</nom>
<adresse>Djerba Tunisie</adresse>
<telephone>+21675600000</telephone>
<fax>+21675600001</fax>
<email>hopital.djerba@rns.tn</email>
</laboratoire>
<typeAnalyse>Hematologie</typeAnalyse>
<tests>
<test nom="Hemoglobine"><valeur unite="g/dL">10.2</valeur><valeurUsuelle>12 - 16</valeurUsuelle></test>
<test nom="Globules Blancs"><valeur unite="10^3/uL">2.9</valeur><valeurUsuelle>4 - 10</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Anemie et immunite faible</conclusion>
</analyse>

<analyse id="A2022_02">
<dateAnalyse><date>2022-01-28</date><heure>09:00:00</heure></dateAnalyse>
<laboratoire>
<nom>Laboratoire Pasteur</nom>
<adresse>Djerba Tunisie</adresse>
<telephone>+21675611111</telephone>
<fax>+21675622222</fax>
<email>pasteur.lab@gmail.com</email>
</laboratoire>
<typeAnalyse>Fer</typeAnalyse>
<tests>
<test nom="Ferritine"><valeur unite="ng/ml">12</valeur><valeurUsuelle>30 - 400</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Carence severe</conclusion>
</analyse>

<analyse id="A2022_03">
<dateAnalyse><date>2022-02-14</date><heure>08:40:00</heure></dateAnalyse>
<laboratoire>
<nom>Laboratoire Bouzidi</nom>
<adresse>Zarzis Tunisie</adresse>
<telephone>+21675694329</telephone>
<fax>+21698430029</fax>
<email>labouzidihassen1@gmail.com</email>
</laboratoire>
<typeAnalyse>Inflammation</typeAnalyse>
<tests>
<test nom="CRP"><valeur unite="mg/L">11</valeur><valeurUsuelle>0 - 5</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Inflammation elevee</conclusion>
</analyse>

<analyse id="A2022_04">
<dateAnalyse><date>2022-03-05</date><heure>10:00:00</heure></dateAnalyse>
<laboratoire>
<nom>Clinique Djerba</nom>
<adresse>Djerba Midoun</adresse>
<telephone>+21675700000</telephone>
<fax>+21675700001</fax>
<email>clinique@djerba.tn</email>
</laboratoire>
<typeAnalyse>Renal</typeAnalyse>
<tests>
<test nom="Creatinine"><valeur unite="mg/L">13</valeur><valeurUsuelle>6 - 12</valeurUsuelle></test>
</tests>
<conclusion statut="surveiller">Fonction renale a surveiller</conclusion>
</analyse>

<analyse id="A2022_05">
<dateAnalyse><date>2022-03-22</date><heure>09:20:00</heure></dateAnalyse>
<laboratoire>
<nom>Laboratoire Pasteur</nom>
<adresse>Djerba Tunisie</adresse>
<telephone>+21675611111</telephone>
<fax>+21675622222</fax>
<email>pasteur.lab@gmail.com</email>
</laboratoire>
<typeAnalyse>Marqueur Tumoral</typeAnalyse>
<tests>
<test nom="CEA"><valeur unite="ng/ml">7.2</valeur><valeurUsuelle>0 - 3</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Evolution tumorale</conclusion>
</analyse>

<analyse id="A2022_06">
<dateAnalyse><date>2022-04-10</date><heure>08:50:00</heure></dateAnalyse>
<laboratoire>
<nom>Laboratoire Bouzidi</nom>
<adresse>Zarzis Tunisie</adresse>
<telephone>+21675694329</telephone>
<fax>+21698430029</fax>
<email>labouzidihassen1@gmail.com</email>
</laboratoire>
<typeAnalyse>Hormonologie</typeAnalyse>
<tests>
<test nom="TSH"><valeur unite="uIU/ml">0.42</valeur><valeurUsuelle>0.34 - 5.60</valeurUsuelle></test>
</tests>
<conclusion statut="normal">Fonction hormonale stable</conclusion>
</analyse>

<analyse id="A2022_07">
<dateAnalyse><date>2022-05-02</date><heure>09:00:00</heure></dateAnalyse>
<laboratoire>
<nom>Hopital Regional de Djerba</nom>
<adresse>Djerba Tunisie</adresse>
<telephone>+21675600000</telephone>
<fax>+21675600001</fax>
<email>hopital.djerba@rns.tn</email>
</laboratoire>
<typeAnalyse>Biochimie</typeAnalyse>
<tests>
<test nom="Albumine"><valeur unite="g/L">27</valeur><valeurUsuelle>35 - 50</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Etat nutritionnel faible</conclusion>
</analyse>

<analyse id="A2022_08">
<dateAnalyse><date>2022-05-20</date><heure>09:30:00</heure></dateAnalyse>
<laboratoire>
<nom>Clinique Djerba</nom>
<adresse>Djerba Midoun</adresse>
<telephone>+21675700000</telephone>
<fax>+21675700001</fax>
<email>clinique@djerba.tn</email>
</laboratoire>
<typeAnalyse>Glycemie</typeAnalyse>
<tests>
<test nom="Glycemie"><valeur unite="g/L">1.3</valeur><valeurUsuelle>0.7 - 1.1</valeurUsuelle></test>
</tests>
<conclusion statut="surveiller">Hyperglycemie</conclusion>
</analyse>

<analyse id="A2022_09">
<dateAnalyse><date>2022-06-12</date><heure>08:30:00</heure></dateAnalyse>
<laboratoire>
<nom>Laboratoire Pasteur</nom>
<adresse>Djerba Tunisie</adresse>
<telephone>+21675611111</telephone>
<fax>+21675622222</fax>
<email>pasteur.lab@gmail.com</email>
</laboratoire>
<typeAnalyse>Hematologie</typeAnalyse>
<tests>
<test nom="Hemoglobine"><valeur unite="g/dL">9.6</valeur><valeurUsuelle>12 - 16</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Anemie severe</conclusion>
</analyse>

<analyse id="A2022_10">
<dateAnalyse><date>2022-07-01</date><heure>08:45:00</heure></dateAnalyse>
<laboratoire>
<nom>Hopital Regional de Djerba</nom>
<adresse>Djerba Tunisie</adresse>
<telephone>+21675600000</telephone>
<fax>+21675600001</fax>
<email>hopital.djerba@rns.tn</email>
</laboratoire>
<typeAnalyse>Immunologie</typeAnalyse>
<tests>
<test nom="Lymphocytes"><valeur unite="10^3/uL">0.8</valeur><valeurUsuelle>1.5 - 4</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Immunite tres faible</conclusion>
</analyse>

<analyse id="A2022_11">
<dateAnalyse><date>2022-08-03</date><heure>09:00:00</heure></dateAnalyse>
<laboratoire>
<nom>Laboratoire Bouzidi</nom>
<adresse>Zarzis Tunisie</adresse>
<telephone>+21675694329</telephone>
<fax>+21698430029</fax>
<email>labouzidihassen1@gmail.com</email>
</laboratoire>
<typeAnalyse>Fer</typeAnalyse>
<tests>
<test nom="Ferritine"><valeur unite="ng/ml">9</valeur><valeurUsuelle>30 - 400</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Carence critique</conclusion>
</analyse>

<analyse id="A2022_12">
<dateAnalyse><date>2022-09-10</date><heure>09:20:00</heure></dateAnalyse>
<laboratoire>
<nom>Clinique Djerba</nom>
<adresse>Djerba Midoun</adresse>
<telephone>+21675700000</telephone>
<fax>+21675700001</fax>
<email>clinique@djerba.tn</email>
</laboratoire>
<typeAnalyse>Inflammation</typeAnalyse>
<tests>
<test nom="CRP"><valeur unite="mg/L">13</valeur><valeurUsuelle>0 - 5</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Inflammation persistante</conclusion>
</analyse>

<analyse id="A2022_13">
<dateAnalyse><date>2022-10-05</date><heure>08:30:00</heure></dateAnalyse>
<laboratoire>
<nom>Hopital Regional de Djerba</nom>
<adresse>Djerba Tunisie</adresse>
<telephone>+21675600000</telephone>
<fax>+21675600001</fax>
<email>hopital.djerba@rns.tn</email>
</laboratoire>
<typeAnalyse>Renal</typeAnalyse>
<tests>
<test nom="Uree"><valeur unite="g/L">0.52</valeur><valeurUsuelle>0.15 - 0.45</valeurUsuelle></test>
</tests>
<conclusion statut="surveiller">Augmentation</conclusion>
</analyse>

<analyse id="A2022_14">
<dateAnalyse><date>2022-11-15</date><heure>09:10:00</heure></dateAnalyse>
<laboratoire>
<nom>Laboratoire Pasteur</nom>
<adresse>Djerba Tunisie</adresse>
<telephone>+21675611111</telephone>
<fax>+21675622222</fax>
<email>pasteur.lab@gmail.com</email>
</laboratoire>
<typeAnalyse>Marqueur Tumoral</typeAnalyse>
<tests>
<test nom="CA19-9"><valeur unite="U/ml">62</valeur><valeurUsuelle>0 - 37</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Augmentation importante</conclusion>
</analyse>

<analyse id="A2022_15">
<dateAnalyse><date>2022-12-20</date><heure>08:55:00</heure></dateAnalyse>
<laboratoire>
<nom>Laboratoire Bouzidi</nom>
<adresse>Zarzis Tunisie</adresse>
<telephone>+21675694329</telephone>
<fax>+21698430029</fax>
<email>labouzidihassen1@gmail.com</email>
</laboratoire>
<typeAnalyse>Vitamine</typeAnalyse>
<tests>
<test nom="Vitamine D"><valeur unite="ng/ml">14</valeur><valeurUsuelle>30 - 100</valeurUsuelle></test>
</tests>
<conclusion statut="surveiller">Carence</conclusion>
</analyse>

<analyse id="A2022_16">
<dateAnalyse><date>2022-12-22</date><heure>09:30:00</heure></dateAnalyse>
<laboratoire>
<nom>Clinique Djerba</nom>
<adresse>Djerba Midoun</adresse>
<telephone>+21675700000</telephone>
<fax>+21675700001</fax>
<email>clinique@djerba.tn</email>
</laboratoire>
<typeAnalyse>Biochimie</typeAnalyse>
<tests>
<test nom="Calcium"><valeur unite="mmol/L">2.0</valeur><valeurUsuelle>2.2 - 2.6</valeurUsuelle></test>
</tests>
<conclusion statut="surveiller">Legere hypocalcemie</conclusion>
</analyse>

<analyse id="A2022_17">
<dateAnalyse><date>2022-12-26</date><heure>08:20:00</heure></dateAnalyse>
<laboratoire>
<nom>Hopital Regional de Djerba</nom>
<adresse>Djerba Tunisie</adresse>
<telephone>+21675600000</telephone>
<fax>+21675600001</fax>
<email>hopital.djerba@rns.tn</email>
</laboratoire>
<typeAnalyse>Immunologie</typeAnalyse>
<tests>
<test nom="Neutrophiles"><valeur unite="10^3/uL">1.0</valeur><valeurUsuelle>2 - 7</valeurUsuelle></test>
</tests>
<conclusion statut="critique">Neutropenie</conclusion>
</analyse>

<analyse id="A2022_18">
<dateAnalyse><date>2022-12-30</date><heure>08:50:00</heure></dateAnalyse>
<laboratoire>
<nom>Laboratoire Pasteur</nom>
<adresse>Djerba Tunisie</adresse>
<telephone>+21675611111</telephone>
<fax>+21675622222</fax>
<email>pasteur.lab@gmail.com</email>
</laboratoire>
<typeAnalyse>Biochimie</typeAnalyse>
<tests>
<test nom="Sodium"><valeur unite="mmol/L">132</valeur><valeurUsuelle>135 - 145</valeurUsuelle></test>
</tests>
<conclusion statut="surveiller">Hyponatremie</conclusion>
</analyse>

</analyses>

=== napster2005/Amel-Reminder/analyses2025.xml
<?xml version="1.0" encoding="UTF-8"?>

<analyses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="analyses.xsd"
patientRef="P01">

<analyse id="A2025_01">
    <dateAnalyse>
        <date>2025-01-08</date>
        <heure>08:10:00</heure>
    </dateAnalyse>
    <laboratoire>
        <nom>Hopital Charles Nicolle</nom>
        <adresse>Tunis Tunisie</adresse>
        <telephone>+21671320000</telephone>
        <fax>+21671320001</fax>
        <email>charles.nicolle@rns.tn</email>
    </laboratoire>
    <typeAnalyse>Hematologie</typeAnalyse>
    <tests>
        <test nom="Hemoglobine">
            <valeur unite="g/dL">13.5</valeur>
            <valeurUsuelle>12 - 16</valeurUsuelle>
        </test>
        <test nom="Plaquettes">
            <valeur unite="10^3/uL">250</valeur>
            <valeurUsuelle>150 - 400</valeurUsuelle>
        </test>
    </tests>
    <conclusion statut="normal">Bilan hematologique normal</conclusion>
</analyse>

<analyse id="A2025_02">
    <dateAnalyse>
        <date>2025-02-20</date>
        <heure>09:30:00</heure>
    </dateAnalyse>
    <laboratoire>
        <nom>Laboratoire Lac 2</nom>
        <adresse>Tunis Tunisie</adresse>
        <telephone>+21671987654</telephone>
        <fax>+21671987655</fax>
        <email>lab.lac2@gmail.com</email>
    </laboratoire>
    <typeAnalyse>Diabete</typeAnalyse>
    <tests>
        <test nom="HbA1c">
            <valeur unite="%">7.8</valeur>
            <valeurUsuelle>4 - 6</valeurUsuelle>
        </test>
    </tests>
    <conclusion statut="surveiller">Diabete mal equilibre</conclusion>
</analyse>

<analyse id="A2025_03">
    <dateAnalyse>
        <date>2025-03-15</date>
        <heure>08:45:00</heure>
    </dateAnalyse>
    <laboratoire>
        <nom>Clinique El Manar</nom>
        <adresse>Tunis Tunisie</adresse>
        <telephone>+21671700000</telephone>
        <fax>+21671700001</fax>
        <email>clinique.manar@tn.com</email>
    </laboratoire>
    <typeAnalyse>Pulmonaire</typeAnalyse>
    <tests>
        <test nom="SpO2">
            <valeur unite="%">88</valeur>
            <valeurUsuelle>95 - 100</valeurUsuelle>
        </test>
    </tests>
    <conclusion statut="critique">Hypoxie importante</conclusion>
</analyse>

<analyse id="A2025_04">
    <dateAnalyse>
        <date>2025-04-22</date>
        <heure>10:00:00</heure>
    </dateAnalyse>
    <laboratoire>
        <nom>Laboratoire Pasteur</nom>
        <adresse>Tunis Tunisie</adresse>
        <telephone>+21675611111</telephone>
        <fax>+21675622222</fax>
        <email>pasteur.lab@gmail.com</email>
    </laboratoire>
    <typeAnalyse>Foie</typeAnalyse>
    <tests>
        <test nom="ALAT">
            <valeur unite="U/L">80</valeur>
            <valeurUsuelle>10 - 40</valeurUsuelle>
        </test>
        <test nom="ASAT">
            <valeur unite="U/L">70</valeur>
            <valeurUsuelle>10 - 40</valeurUsuelle>
        </test>
    </tests>
    <conclusion statut="surveiller">Atteinte hepatique</conclusion>
</analyse>

<analyse id="A2025_05">
    <dateAnalyse>
        <date>2025-05-18</date>
        <heure>09:15:00</heure>
    </dateAnalyse>
    <laboratoire>
        <nom>Hopital Sahloul</nom>
        <adresse>Sousse Tunisie</adresse>
        <telephone>+21673250000</telephone>
        <fax>+21673250001</fax>
        <email>sahloul@rns.tn</email>
    </laboratoire>
    <typeAnalyse>Renal</typeAnalyse>
    <tests>
        <test nom="Creatinine">
            <valeur unite="mg/L">20</valeur>
            <valeurUsuelle>6 - 12</valeurUsuelle>
        </test>
    </tests>
    <conclusion statut="critique">Insuffisance renale avancee</conclusion>
</analyse>

<analyse id="A2025_06">
    <dateAnalyse>
        <date>2025-06-25</date>
        <heure>08:30:00</heure>
    </dateAnalyse>
    <laboratoire>
        <nom>Laboratoire Bouzidi</nom>
        <adresse>Zarzis Tunisie</adresse>
        <telephone>+21675694329</telephone>
        <fax>+21698430029</fax>
        <email>labouzidihassen1@gmail.com</email>
    </laboratoire>
    <typeAnalyse>Hormonal</typeAnalyse>
    <tests>
        <test nom="TSH">
            <valeur unite="uIU/ml">0.1</valeur>
            <valeurUsuelle>0.34 - 5.60</valeurUsuelle>
        </test>
    </tests>
    <conclusion statut="critique">Hyperthyroidie</conclusion>
</analyse>

<analyse id="A2025_07">
    <dateAnalyse>
        <date>2025-07-30</date>
        <heure>09:40:00</heure>
    </dateAnalyse>
    <laboratoire>
        <nom>Clinique Djerba</nom>
        <adresse>Djerba Midoun</adresse>
        <telephone>+21675700000</telephone>
        <fax>+21675700001</fax>
        <email>clinique@djerba.tn</email>
    </laboratoire>
    <typeAnalyse>Electrolytes</typeAnalyse>
    <tests>
        <test nom="Sodium">
            <valeur unite="mmol/L">150</valeur>
            <valeurUsuelle>135 - 145</valeurUsuelle>
        </test>
    </tests>
    <conclusion statut="surveiller">Hypernatremie</conclusion>
</analyse>

<analyse id="A2025_08">
    <dateAnalyse>
        <date>2025-09-12</date>
        <heure>08:20:00</heure>
    </dateAnalyse>
    <laboratoire>
        <nom>Hopital Regional de Djerba</nom>
        <adresse>Djerba Tunisie</adresse>
        <telephone>+21675600000</telephone>
        <fax>+21675600001</fax>
        <email>hopital.djerba@rns.tn</email>
    </laboratoire>
    <typeAnalyse>Vitamine</typeAnalyse>
    <tests>
        <test nom="Vitamine B12">
            <valeur unite="pg/ml">900</valeur>
            <valeurUsuelle>174 - 878</valeurUsuelle>
        </test>
    </tests>
    <conclusion statut="surveiller">Excès vitamine B12</conclusion>
</analyse>

</analyses>
